# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    container:
      image: "centos:7"

    steps:
    - uses: actions/checkout@v1

    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: '1.23.4'

    - name: Build
      run: sudo yum install -y libpcap-devel && go build

    - name: Archive production artifacts
      uses: actions/upload-artifact@v1
      with:
          name: tm
          path: |
            ./timemonitor
